Prepara avaliador para v3
betrybe/mongodb-query-evaluator-action pull request #8
Opened 2021-01-15 10:42 UTC by jeanpsv

- Retira output variable `pr-number` pois não é mais utilizada (utilizamos `github.event.number`)
- Retira comando que faz clone da versão que está na _branch_ principal. Essa responsabilidade será de uma outra GitHub Action

2021-01-15 10:46 UTC, hurrycaner approved these changes

2021-01-15 14:03 UTC, inaC requested changes

2021-01-15 14:03 UTC, inaC commented on scripts/entrypoint.sh
>  scripts/generate_result.sh "/github/workspace/$CHALLENGES_DIR" "/github/master-repo/.trybe" "/github/workspace/$DB_RESTORE_DIR"
O comando que fazia o clone tornava o código disponível no runner no caminho `/github/master-repo/`. Agora que foi removido, esse script continuaria funcionando uma vez ele continua recebendo como parâmetro `"/github/master-repo/.trybe"`?

2021-01-18 13:16 UTC, eucleciojosias requested changes

2021-01-18 13:16 UTC, eucleciojosias commented on scripts/entrypoint.sh
>  scripts/generate_result.sh "/github/workspace/$CHALLENGES_DIR" "/github/master-repo/.trybe" "/github/workspace/$DB_RESTORE_DIR"
Ajustar ponto apontado pelo @inaC

2021-01-19 16:44 UTC, eucleciojosias approved these changes

2021-01-19 17:24 UTC, inaC approved these changes

2021-01-19 17:42 UTC, LeandroLM approved these changes

2021-01-26 12:19 UTC, merged