imp: renomeia inputs e adc PR author username
betrybe/mongodb-query-evaluator-action pull request #9
Opened 2021-01-22 18:05 UTC by eucleciojosias

Renomeia inputs para usar como envvars

2021-01-25 12:29 UTC, gknedo approved these changes

2021-01-25 15:43 UTC, jeanpsv approved these changes

2021-01-26 17:07 UTC, inaC requested changes

2021-01-26 17:07 UTC, inaC commented on README.md
> +  Pull Request author username.
Seria interessante atualizar em como consumir a action com esses 3 inputs obrigatórios, na seção [`Evaluator Action`](https://github.com/betrybe/mongodb-query-evaluator-action/blob/f42ef80f6c29ab1fae4daceb6f8de5e2d723c68a/README.md#evaluator-action), não?

2021-01-26 20:43 UTC, inaC approved these changes

2021-02-01 16:32 UTC, hurrycaner approved these changes

2021-02-01 22:31 UTC, merged